# --- GEMEINSAME EINSTELLUNGEN ---
quarkus.http.host=0.0.0.0

# Deployment Metadaten
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=GossenreiterThomas
quarkus.container-image.name=taskosaurus-backend
quarkus.kubernetes.image-pull-secrets=ghcr-secret

# --- DEV MODE (Lokale Entwicklung mit H2) ---
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:taskosaurus;DB_CLOSE_DELAY=-1
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql

# --- PROD MODE (Kubernetes / PostgreSQL) ---
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.hibernate-orm.database.generation=update
# Wir nutzen in Prod KEIN sql-load-script, um Datenverlust zu vermeiden!
# %prod.quarkus.hibernate-orm.sql-load-script=no-file 

# Kubernetes spezifische Config
quarkus.kubernetes.service-type=load-balancer
quarkus.kubernetes.port=8080
quarkus.kubernetes.env.vars.quarkus-datasource-jdbc-url=jdbc:postgresql://postgres-db:5432/taskosaurus
quarkus.kubernetes.env.vars.quarkus-datasource-username=admin
quarkus.kubernetes.env.vars.quarkus-datasource-password=geheim

# Ingress
quarkus.kubernetes.ingress.expose=true
quarkus.kubernetes.ingress.host=it210142.cloud.htl-leonding.ac.at
quarkus.kubernetes.ingress.target-port=http
quarkus.kubernetes.ingress.annotations."nginx.ingress.kubernetes.io/ssl-redirect"="false"
quarkus.kubernetes.ingress.class=nginx