//quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost:9092/./db

quarkus.hibernate-orm.database.generation=drop-and-create
//quarkus.datasource.db-version=2.1.0
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.http.host=0.0.0.0


// Deployment
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=GossenreiterThomas
quarkus.container-image.name=taskosaurus-backend

quarkus.kubernetes.image-pull-secrets=ghcr-secret

quarkus.kubernetes.service-type=load-balancer

quarkus.kubernetes.port=8080

# Der Hostname im Cluster entspricht dem Service-Namen oben
quarkus.kubernetes.env.vars.quarkus-datasource-jdbc-url=jdbc:postgresql://postgres-db:5432/taskosaurus
quarkus.kubernetes.env.vars.quarkus-datasource-username=admin
quarkus.kubernetes.env.vars.quarkus-datasource-password=geheim
quarkus.datasource.db-kind=postgresql

quarkus.kubernetes.ingress.expose=true

quarkus.kubernetes.ingress.host=it210142.cloud.htl-leonding.ac.at

quarkus.kubernetes.ingress.target-port=http

quarkus.kubernetes.ingress.annotations."nginx.ingress.kubernetes.io/ssl-redirect"="false"
quarkus.kubernetes.ingress.class=nginx
