INSERT INTO Question (question) VALUES ('Wer würde am ehesten versuchen in einer Fremdsprache zu kommunizieren, indem er einfach deutsche Wörter mit einem Akzent ausspricht?');
INSERT INTO Question (question) VALUES ('Wer von uns würde am wenigsten das Haus verlassen, wenn der Handyakku fast leer ist, und deshalb lieber zu spät kommen?');
INSERT INTO Question (question) VALUES ('Wer lebt am stärksten nach dem Motto "Man lebt nur einmal im Leben"?');
INSERT INTO Question (question) VALUES ('Wer würde eine gesamte Gruppenreise dokumentieren, aber die Fotos nie mit uns teilen?');
INSERT INTO Question (question) VALUES ('Wer überreagiert am schnellsten?');
INSERT INTO Question (question) VALUES ('Jeder in der Gruppe zeigt dir einen Song. Wer hat den unvorhersehbarsten Musikgeschmack?');
INSERT INTO Question (question) VALUES ('Wer würde es am kürzesten in einer dreckigen Wohnung aushalten? Putzen ist nicht erlaubt!');
INSERT INTO Question (question) VALUES ('Wer ist am schnellsten Teil von neuen Trends?');
INSERT INTO Question (question) VALUES ('Wer würde am ehesten kriminell werden, um einem Freund bei etwas zu helfen?');
INSERT INTO Question (question) VALUES ('Wer würde am ehesten versuchen, sich mit Wortwitz und Charme aus einem Strafzettel herauszureden?');
INSERT INTO Question (question) VALUES ('Wer könnte die beste TikTok-Tanzperformance hinlegen?');
INSERT INTO Question (question) VALUES ('Wen würde man öffentlich am wenigsten als "politisch korrekt" einstufen?');
INSERT INTO Question (question) VALUES ('Ganz alleine in einem leeren Raum: Wer würde am schnellsten die Nerven verlieren?');

INSERT INTO GroupEntity (name, link) VALUES ('Familie', 'http://192.168.137.135:8080/api/group/join/1');
INSERT INTO GroupEntity (name, link) VALUES ('4AHITM', 'http://192.168.137.135:8080/api/group/join/2');
INSERT INTO GroupEntity (name, link) VALUES ('Die 5 Freunde', 'http://192.168.137.135:8080/api/group/join/3');
INSERT INTO GroupEntity (name, link) VALUES ('Die 3 ???', 'http://192.168.173.137:8080/api/group/join/4');

INSERT INTO Player (name) VALUES('Isabella');
INSERT INTO Player (name) VALUES('Max');
INSERT INTO Player (name) VALUES('Herbert');
INSERT INTO Player (name) VALUES('Frederike');
INSERT INTO Player (name) VALUES('Gertrude');
INSERT INTO Player (name) VALUES('Thomas');
INSERT INTO Player (name) VALUES('Kinga');
INSERT INTO Player (name) VALUES('Timon');
INSERT INTO Player (name) VALUES('Lien');
INSERT INTO Player (name) VALUES('Stefanie');
INSERT INTO Player (name) VALUES('Christof');
INSERT INTO Player (name) VALUES('Tobi');
INSERT INTO Player (name) VALUES('Timmy');
INSERT INTO Player (name) VALUES('Georgina');
INSERT INTO Player (name) VALUES('Julian');
INSERT INTO Player (name) VALUES('Anne');
INSERT INTO Player (name) VALUES('Peter');
INSERT INTO Player (name) VALUES('Bob');

INSERT INTO Player_Group (player_id, group_id) VALUES (1, 1);
INSERT INTO Player_Group (player_id, group_id) VALUES (2, 1);
INSERT INTO Player_Group (player_id, group_id) VALUES (3, 1);
INSERT INTO Player_Group (player_id, group_id) VALUES (4, 1);
INSERT INTO Player_Group (player_id, group_id) VALUES (5, 1);
INSERT INTO Player_Group (player_id, group_id) VALUES (1, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (6, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (7, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (8, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (9, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (10, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (11, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (12, 2);
INSERT INTO Player_Group (player_id, group_id) VALUES (1, 3);
INSERT INTO Player_Group (player_id, group_id) VALUES (13, 3);
INSERT INTO Player_Group (player_id, group_id) VALUES (14, 3);
INSERT INTO Player_Group (player_id, group_id) VALUES (15, 3);
INSERT INTO Player_Group (player_id, group_id) VALUES (16, 3);
INSERT INTO Player_Group (player_id, group_id) VALUES (1, 4);
INSERT INTO Player_Group (player_id, group_id) VALUES (17, 4);
INSERT INTO Player_Group (player_id, group_id) VALUES (18, 4);

INSERT INTO GroupQuestion (question_id, group_id, date) VALUES (7, 1, CURRENT_DATE);
INSERT INTO GroupQuestion (question_id, group_id, date) VALUES (9, 2, CURRENT_DATE);

--INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (1, 2, 1);
--INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (2, 2, 1);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (3, 5, 1);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (4, 2, 1);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (5, 4, 1);

INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (11, 12, 2);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (7, 11, 2);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (8, 12, 2);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (9, 6, 2);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (10, 8, 2);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (12, 12, 2);
INSERT INTO GroupQuestionAnswer (answering_player_id, answer, group_question_id) VALUES (13, 8, 2);
