GET localhost:8080/api/group/list

###
 POST localhost:8080/api/group/create
Content-Type: application/json

{
    "name": "Gruppe haxi"
}

###

POST localhost:8080/api/player/create
Content-Type: application/json

{
  "name": "Isabella"
}

###

POST localhost:8080/api/group/join/1
Content-Type: application/json

{
  "id": 1,
  "name": "Isabella"
}

### Invalid Groupid
